New post for additional Java to create multiple VSD objects
nuagenetworks/nuagenetworks.github.io pull request #34
Opened 2018-02-16 20:54 UTC by paquel

Added new 'md' file and some image files for a new posting that describes how to construct and remove a VSD network layout of Enterprise, Domain, Zone and Subnet objects.

2018-02-16 21:54 UTC, pdellaert requested changes
One typo, one small remark and one remark about ip addresses which i've mentioned everywhere it was appropriate (so repeated)

Overal great blog post! Thanks :)

2018-02-16 21:54 UTC, pdellaert commented on _posts/2018-02-16-Java-Time2.md
> +Note that in the constructor at Line 1, there is a `VSDSession` argument.  A `VSDSsssion` object establishes a secure HTTP connection to a VSD instance.  It is similar to how you would create a conne
`VSDSsssion` -> `VSDSession`

2018-02-16 21:54 UTC, pdellaert commented on _posts/2018-02-16-Java-Time2.md
> +Line 8 of the `createEnterprise` method is similar to Line 4 of the `fetchEnterprise` method.  It provides us with a 'Me' root object onto which we can attach a new Enterprise object.  In Line 9, we
`'Me'` -> `` `Me` ``

2018-02-16 21:54 UTC, pdellaert commented on _posts/2018-02-16-Java-Time2.md
> +    private String url = "https://135.228.4.108:8443"; // 1
Don't use a 135.... IP in documentation, use one from https://tools.ietf.org/html/rfc5737

Suggestion: `198.51.100.108`

2018-02-16 21:54 UTC, pdellaert commented on _posts/2018-02-16-Java-Time2.md
> +    private String url = "https://135.228.4.108:8443";
Don't use a 135.... IP in documentation, use one from https://tools.ietf.org/html/rfc5737

Suggestion: `198.51.100.108`

2018-02-16 21:54 UTC, pdellaert commented on _posts/2018-02-16-Java-Time2.md
> +    private String url = "https://135.228.4.108:8443";
Don't use a 135.... IP in documentation, use one from https://tools.ietf.org/html/rfc5737

Suggestion: `198.51.100.108`

2018-02-16 21:54 UTC, pdellaert commented on _posts/2018-02-16-Java-Time2.md
> +    private String url = "https://135.228.4.108:8443";
Don't use a 135.... IP in documentation, use one from https://tools.ietf.org/html/rfc5737

Suggestion: `198.51.100.108`

2018-02-16 21:54 UTC, pdellaert commented on _posts/2018-02-16-Java-Time2.md
> +    private String url = "https://135.228.4.108:8443";
Don't use a 135.... IP in documentation, use one from https://tools.ietf.org/html/rfc5737

Suggestion: `198.51.100.108`

2018-02-16 21:54 UTC, pdellaert commented on _posts/2018-02-16-Java-Time2.md
> +In order to remove VSD objects, there are dependency rules that must be followed, based on parent-child relationships within the object tree.  For example, to remove a Zone object, there must not be
Just a note that this is not exactly true. You can actually delete a whole domain without first deleting the subnet and zones, as long as there are no vPorts present.

However, for the sake of your blog post, no need to make a change here :)

2018-02-16 21:54 UTC, pdellaert commented on _posts/2018-02-16-Java-Time2.md
> +In Line 9 of the `fetchAllTemplatesForEnterprise` method, we gather all Domain Template children for a given Enterprise into a Fetcher.  Then in Lines 10 and 11, we c
Don't use a 135.... IP in documentation, use one from https://tools.ietf.org/html/rfc5737

Suggestion: `198.51.100.108`

2018-02-19 14:03 UTC, paquel commented
Hi Philippe:  Thank you so much for the quick review.  

      From: Philippe Dellaert <notifications@github.com>
 To: nuagenetworks/nuagenetworks.github.io <nuagenetworks.github.io@noreply.github.com> 
Cc: paquel <lenpaquette@yahoo.com>; Author <author@noreply.github.com>
 Sent: Friday, February 16, 2018 4:54 PM
 Subject: Re: [nuagenetworks/nuagenetworks.github.io] New post for additional Java to create multiple VSD objects (#34)
   
@pdellaert requested changes on this pull request.One typo, one small remark and one remark about ip addresses which i've mentioned everywhere it was appropriate (so repeated)Overal great blog post! Thanks :)In _posts/2018-02-16-Java-Time2.md:> +    public void deleteEnterprise(Enterprise enterprise) { // 12
+        if (enterprise == null) {
+            System.out.println("Enterprise does not exist");
+        } else {
+            System.out.println("Enterprise " + enterprise.getName() + " will be deleted");
+            try {
+                enterprise.delete(); // 13
+            } catch (RestException e) {
+                e.printStackTrace();
+            }
+        }
+    }
+}
+{% endhighlight %}
+
+Note that in the constructor at Line 1, there is a `VSDSession` argument.  A `VSDSsssion` object establishes a secure HTTP connection to a VSD instance.  It is similar to how you would create a connection to a database before running SQL queries.  Before calling methods in this class, we will assume that a VSD session has already been established and started by `NetworkBuilder`.
VSDSsssion -> VSDSessionIn _posts/2018-02-16-Java-Time2.md:> +                enterprise.delete(); // 13
+            } catch (RestException e) {
+                e.printStackTrace();
+            }
+        }
+    }
+}
+{% endhighlight %}
+
+Note that in the constructor at Line 1, there is a `VSDSession` argument.  A `VSDSsssion` object establishes a secure HTTP connection to a VSD instance.  It is similar to how you would create a connection to a database before running SQL queries.  Before calling methods in this class, we will assume that a VSD session has already been established and started by `NetworkBuilder`.
+
+In Line 2 of the `verifyEnterprise` method, we perform a search for an existing VSD Enterprise object that matches the name for our enterprise that is passed in via `NetworkDescriptor`. If the Enterprise already exists, then we return that Enterprise object.  If the Enterprise does not exist, then in Line 3 we call the `createEnterprise` method to create and return a new Enterprise object.
+
+In the `fetchEnterprise` method at Line 4, we instantiate a `Me` object to serve as the root for all of our enterprise specific network objects.  Line 5 sets up a search filter based on the name of our enterprise.  In Line 6, we create an instance of `EnterprisesFetcher`.  The VSPK provides "Fetchers" for all entity types in the VSD to offer convenience methods for operating on collections of VSD objects.  Line 7 calls the `getFirst` method of the Fetcher to retrieve the Enterprise object matching the name in the search filter.
+
+Line 8 of the `createEnterprise` method is similar to Line 4 of the `fetchEnterprise` method.  It provides us with a 'Me' root object onto which we can attach a new Enterprise object.  In Line 9, we call the constructor of the VSPK Enterprise class to create a brand new Enterprise object and then in Line 10 we assign our enterprise name.  Finally, in Line 11, we create a new child Enterprise object.
'Me' -> `Me`In _posts/2018-02-16-Java-Time2.md:> +Line 8 of the `createEnterprise` method is similar to Line 4 of the `fetchEnterprise` method.  It provides us with a 'Me' root object onto which we can attach a new Enterprise object.  In Line 9, we call the constructor of the VSPK Enterprise class to create a brand new Enterprise object and then in Line 10 we assign our enterprise name.  Finally, in Line 11, we create a new child Enterprise object.
+
+The method `deleteEnterprise` will be covered later when we discuss how to remove our network layout from the VSD.
+
+# Adding the Enterprise to our Network
+
+Here is the updated version of the `NetworkBuilder` class that integrates with `NetworkEnterpriseHandler`.
+
+{% highlight java %}
+import java.util.List;
+import net.nuagenetworks.bambou.RestException;
+import net.nuagenetworks.vspk.v5_0.Enterprise;
+import net.nuagenetworks.vspk.v5_0.VSDSession;
+
+public class NetworkBuilder {
+    private String url = "https://135.228.4.108:8443"; // 1
Don't use a 135.... IP in documentation, use one from https://tools.ietf.org/html/rfc5737Suggestion: 198.51.100.108In _posts/2018-02-16-Java-Time2.md:> +
+Lines 9 to 13 of methods `fetchAllTemplatesForEnterprise` and `deleteTemplate` will be covered later when we discuss how to remove our network layout from the VSD.
+
+# Adding the Domain Template to our Network
+
+Here is the updated version of the `NetworkBuilder` class that integrates with `NetworkDomainTemplateHandler`.  There are 2 minor changes as shown below.  At Line 1, we instantiate the new handler and at Line 2, we call its `verifyTemplate` method with our existing Enterprise object and the `NetworkDescriptor` object which contains the name of our domain template.
+
+{% highlight java %}
+import java.util.List;
+import net.nuagenetworks.bambou.RestException;
+import net.nuagenetworks.vspk.v5_0.DomainTemplate;
+import net.nuagenetworks.vspk.v5_0.Enterprise;
+import net.nuagenetworks.vspk.v5_0.VSDSession;
+
+public class NetworkBuilder {
+    private String url = "https://135.228.4.108:8443";
Don't use a 135.... IP in documentation, use one from https://tools.ietf.org/html/rfc5737Suggestion: 198.51.100.108In _posts/2018-02-16-Java-Time2.md:> +Lines 11 to 15 of methods `fetchAllDomainsForEnterprise` and `deleteDomain` will be covered later when we discuss how to remove our network layout from the VSD.
+
+# Adding the Domain to our Network
+
+Here is the updated version of the `NetworkBuilder` class that integrates with `NetworkDomainHandler`.  There are 2 minor changes as shown below.  At Line 1, we instantiate the new handler and at Line 2, we call its `verifyDomain` method and pass it our existing Enterprise object, Domain Template object and the `NetworkDescriptor` object which contains the name of our domain.
+
+{% highlight java %}
+import java.util.List;
+import net.nuagenetworks.bambou.RestException;
+import net.nuagenetworks.vspk.v5_0.Domain;
+import net.nuagenetworks.vspk.v5_0.DomainTemplate;
+import net.nuagenetworks.vspk.v5_0.Enterprise;
+import net.nuagenetworks.vspk.v5_0.VSDSession;
+
+public class NetworkBuilder {
+    private String url = "https://135.228.4.108:8443";
Don't use a 135.... IP in documentation, use one from https://tools.ietf.org/html/rfc5737Suggestion: 198.51.100.108In _posts/2018-02-16-Java-Time2.md:> +
+# Adding the Zone to our Network
+
+Here is the updated version of the `NetworkBuilder` class that integrates with `NetworkZoneHandler`.  There are 2 minor changes as shown below.  At Line 1, we instantiate the new handler and at Line 2, we call its `verifyZone` method and pass it our existing Domain object and the `NetworkDescriptor` object which contains the name of our zone.
+
+{% highlight java %}
+import java.util.List;
+import net.nuagenetworks.bambou.RestException;
+import net.nuagenetworks.vspk.v5_0.Zone;
+import net.nuagenetworks.vspk.v5_0.Domain;
+import net.nuagenetworks.vspk.v5_0.DomainTemplate;
+import net.nuagenetworks.vspk.v5_0.Enterprise;
+import net.nuagenetworks.vspk.v5_0.VSDSession;
+
+public class NetworkBuilder {
+    private String url = "https://135.228.4.108:8443";
Don't use a 135.... IP in documentation, use one from https://tools.ietf.org/html/rfc5737Suggestion: 198.51.100.108In _posts/2018-02-16-Java-Time2.md:> +# Adding the Subnet to our Network
+
+Here is the updated version of the `NetworkBuilder` class that integrates with `NetworkSubnetHandler`.  There are 2 minor changes as shown below.  At Line 1, we i [...]

2018-02-19 14:55 UTC, paquel commented
@pdellaert Thanks Philippe.  Made suggested changes

2018-02-19 16:42 UTC, pdellaert approved these changes

2018-02-19 16:42 UTC, merged